/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hoangvu.form;


import com.hoangvu.model.ModelUser;

import java.awt.*;

public class ChatTittle extends javax.swing.JPanel {

    public void setToUserName(ModelUser toUser) {
        setToUser(toUser);
        userName.setText(toUser.getUserName());
        if(toUser.isActivateStatus()){
            status.setText("Active Now");
            this.status.setForeground(new Color(3, 178, 53));
        }else{
            status.setText("Offline");
            this.status.setForeground(new Color(126, 126, 126));
        }
    }
    public void updataUser(ModelUser toUser) {
        if(toUser.isActivateStatus()){
            setStatus("Active now");
            this.status.setForeground(new Color(3, 178, 53));
        }else{
            setStatus("Offline");
            this.status.setForeground(new Color(126, 126, 126));
        }
    }
    public ModelUser getToUser() {
        return toUser;
    }

    public void setToUser(ModelUser toUser) {
        this.toUser = toUser;
    }

    /**
     * Creates new form ChatTittle
     */
    private ModelUser toUser;

    public ModelUser getUser() {
        return user;
    }

    public void setUser(ModelUser user) {
        this.user = user;
    }

    private ModelUser user;
    public ChatTittle(ModelUser user) {
        this.user = user;
        initComponents();
    }
    public void setUsername(String username) {
        this.userName.setText(username);
    }

    public void setStatus(String status) {
        this.status.setText(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layer = new javax.swing.JLayeredPane();
        userName = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        callLayer = new javax.swing.JLayeredPane();
        videoCallBt = new javax.swing.JButton();
        callBt = new javax.swing.JButton();

        layer.setLayout(new java.awt.GridLayout(2, 0));

        userName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userName.setText("User Name");
        layer.add(userName);

        status.setForeground(new java.awt.Color(11, 171, 91));
        status.setText("Activate now");
        layer.add(status);

        callLayer.setLayout(new java.awt.GridLayout(0, 2));

        videoCallBt.setBackground(new java.awt.Color(242, 242, 242));
        videoCallBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hoangvu/icon/video-camera.png"))); // NOI18N
        videoCallBt.setBorder(null);
        videoCallBt.setBorderPainted(false);
        videoCallBt.setContentAreaFilled(false);
        videoCallBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        videoCallBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoCallBtActionPerformed(evt);
            }
        });
        callLayer.add(videoCallBt);

        callBt.setBackground(new java.awt.Color(242, 242, 242));
        callBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hoangvu/icon/telephone-call.png"))); // NOI18N
        callBt.setBorder(null);
        callBt.setBorderPainted(false);
        callBt.setContentAreaFilled(false);
        callBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        callLayer.add(callBt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(layer, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(callLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(callLayer)
            .addComponent(layer)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void videoCallBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoCallBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_videoCallBtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton callBt;
    private javax.swing.JLayeredPane callLayer;
    private javax.swing.JLayeredPane layer;
    private javax.swing.JLabel status;
    private javax.swing.JLabel userName;
    private javax.swing.JButton videoCallBt;
    // End of variables declaration//GEN-END:variables
}
