package com.hoangvu.form;

import com.hoangvu.event.PublicEvent;
import com.hoangvu.model.ModelUser;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Admin
 */
public class ItemObject extends javax.swing.JPanel {

    private boolean mouseOver;
    public ModelUser getUser() {
        return toUser;
    }

    private ModelUser toUser;
    public ItemObject(ModelUser toUser) {
        initComponents();
        if (toUser != null){
            lbUserName.setText(toUser.getUserName());
            lbStatus.setForeground(new Color(126, 126, 126));
            activeStatus.setActive(toUser.isActivateStatus());
        }
        this.toUser = toUser;
        init();
    }
    
    public void updataStatus() {
        activeStatus.setActive(toUser.isActivateStatus());
    }

    private void init() {
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent me) {
                setBackground(new Color(230, 230, 230));
                mouseOver = true;
            }

            @Override
            public void mouseExited(MouseEvent me) {
                setBackground(new Color(242, 242, 242));
                mouseOver = false;
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if (mouseOver){
//                    chat.setToUser(toUser);
//                    System.out.println("Press "+toUser.getUserName());
                    PublicEvent.getInstance().getEventMain().selectUser(toUser);
                }
            }
        });
        this.setBackground(new Color(242,242,242));
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent me) {
                setBackground(new Color(230, 230, 230));
            }

            @Override
            public void mouseExited(MouseEvent me) {
                setBackground(new Color(242, 242, 242));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageAvatar = new com.hoangvu.swing.ImageAvatar();
        lbUserName = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        activeStatus = new com.hoangvu.swing.ActiveStatus();

        imageAvatar.setBorderSize(0);
        imageAvatar.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/hoangvu/icon/avatar-45.png"))); // NOI18N
        imageAvatar.setOpaque(true);

        lbUserName.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        lbUserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbUserName.setText("User name");

        lbStatus.setFont(new java.awt.Font("JetBrains Mono", 2, 10)); // NOI18N
        lbStatus.setText("Active status");

        activeStatus.setMaximumSize(new java.awt.Dimension(8, 8));
        activeStatus.setMinimumSize(new java.awt.Dimension(8, 8));
        activeStatus.setPreferredSize(new java.awt.Dimension(8, 8));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imageAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbStatus)
                                                .addGap(2, 2, 2)
                                                .addComponent(activeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(imageAvatar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbUserName)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbStatus)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(activeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hoangvu.swing.ActiveStatus activeStatus;
    private com.hoangvu.swing.ImageAvatar imageAvatar;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbUserName;
    // End of variables declaration//GEN-END:variables
}
