/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hoangvu.form;
import java.awt.*;


public class ToolBar extends javax.swing.JPanel {


    /**
     * Creates new form ToolBar
     */
    public ToolBar(MenuLeft menuLeft) {
        initComponents();
        messageBt.setSelected(true);
        this.menuLeft = menuLeft;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLayeredPane();
        messageBt = new javax.swing.JButton();
        groupBt = new javax.swing.JButton();
        settingBt = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        menu.setOpaque(true);

        messageBt.setBackground(new java.awt.Color(102, 102, 102));
        messageBt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        messageBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hoangvu/icon/chat_unselect.png"))); // NOI18N
        messageBt.setBorder(null);
        messageBt.setBorderPainted(false);
        messageBt.setContentAreaFilled(false);
        messageBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        messageBt.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        messageBt.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hoangvu/icon/chat.png"))); // NOI18N
        messageBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                messageBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                messageBtMouseExited(evt);
            }
        });
        messageBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageBtActionPerformed(evt);
            }
        });

        groupBt.setBackground(new java.awt.Color(102, 102, 102));
        groupBt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        groupBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hoangvu/icon/group_unselect.png"))); // NOI18N
        groupBt.setBorder(null);
        groupBt.setBorderPainted(false);
        groupBt.setContentAreaFilled(false);
        groupBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        groupBt.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        groupBt.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hoangvu/icon/group.png"))); // NOI18N
        groupBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                groupBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                groupBtMouseExited(evt);
            }
        });
        groupBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupBtActionPerformed(evt);
            }
        });

        settingBt.setBackground(new java.awt.Color(102, 102, 102));
        settingBt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        settingBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hoangvu/icon/setting_unselect.png"))); // NOI18N
        settingBt.setBorder(null);
        settingBt.setBorderPainted(false);
        settingBt.setContentAreaFilled(false);
        settingBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingBt.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        settingBt.setHideActionText(true);
        settingBt.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hoangvu/icon/setting.png"))); // NOI18N
        settingBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingBtMouseExited(evt);
            }
        });
        settingBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingBtActionPerformed(evt);
            }
        });

        menu.setLayer(messageBt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menu.setLayer(groupBt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menu.setLayer(settingBt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(messageBt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(groupBt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(settingBt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(messageBt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(groupBt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(settingBt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 419, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void messageBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageBtMouseEntered
        messageBt.setBackground(new Color(234, 234, 234, 255));
        messageBt.setOpaque(true);
    }//GEN-LAST:event_messageBtMouseEntered

    private void messageBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageBtMouseExited
        messageBt.setBackground(new Color(255, 255, 255, 255));
        messageBt.setOpaque(true);
    }//GEN-LAST:event_messageBtMouseExited

    private void messageBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageBtActionPerformed
        if ( !messageBt.isSelected()){
            messageBt.setSelected(true);
            groupBt.setSelected(false);
            settingBt.setSelected(false);
        }
        if (menuLeft != null) {
            menuLeft.showGroup(100);
        }
    }//GEN-LAST:event_messageBtActionPerformed

    private void groupBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupBtMouseEntered
        groupBt.setBackground(new Color(234, 234, 234, 255));
        groupBt.setOpaque(true);
    }//GEN-LAST:event_groupBtMouseEntered

    private void groupBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupBtMouseExited
        groupBt.setBackground(new Color(255, 255, 255, 255));
        groupBt.setOpaque(true);
    }//GEN-LAST:event_groupBtMouseExited

    private void groupBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupBtActionPerformed
        if ( !groupBt.isSelected()){
            messageBt.setSelected(false);
            groupBt.setSelected(true);
            settingBt.setSelected(false);
        }
        if (menuLeft != null) {
            menuLeft.showGroup(5);
        }
    }//GEN-LAST:event_groupBtActionPerformed

    private void settingBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingBtMouseEntered
        settingBt.setBackground(new Color(234, 234, 234, 255));
        settingBt.setOpaque(true);
    }//GEN-LAST:event_settingBtMouseEntered

    private void settingBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingBtMouseExited
        settingBt.setBackground(new Color(255, 255, 255, 255));
        settingBt.setOpaque(true);
    }//GEN-LAST:event_settingBtMouseExited

    private void settingBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingBtActionPerformed
        if ( !settingBt.isSelected()){
            messageBt.setSelected(false);
            groupBt.setSelected(false);
            settingBt.setSelected(true);
        }
        if (menuLeft != null) {
            menuLeft.showGroup(7);
        }
    }//GEN-LAST:event_settingBtActionPerformed
    public void setMenuLeft(MenuLeft menuLeft) {
        this.menuLeft = menuLeft;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton groupBt;
    private javax.swing.JLayeredPane menu;
    private javax.swing.JButton messageBt;
    private javax.swing.JButton settingBt;
    // End of variables declaration//GEN-END:variables
    private MenuLeft menuLeft ;

}
